apiVersion: v1  
kind: Service  
metadata:  
  name: my-app  
spec:  
  type: ClusterIP  # or LoadBalancer if you need an external IP  
  ports:  
    - port: 80  
      targetPort: 80  
  selector:  
    app: my-app  